version: '3.7'
services:
    db:
        image: postgres:10.5
        restart: always


 
        environment:
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=${DB_NAME}
          
        ports:
          - '5434:${DB_PORT}'
        expose:
          - "5432"
        volumes: 
          - ../postgres-data:/var/lib/postgresql/data

        networks:
          - postgres-network


    luqi:
      container_name: liqui
      image: liquibase/liquibase
      command: --changeLogFile=/change-log.xml update --url=jdbc:postgresql://db:5432/postgres --username=postgres --password=postgres
      volumes:
        - ./src/database/change-log.xml:/liquibase/change-log.xml
        - ./src/database/entities/:/liquibase/entities/
      depends_on:
          db:
            condition: service_started
      networks:
        - postgres-network

    ts-node-docker:
        build:
          context: ./
          dockerfile: Dockerfile
        depends_on:
          luqi:
            condition: service_started

        volumes:
          - ./src:/home/node/app/src
          - ./nodemon.json:/home/node/app/nodemon.json
        container_name: ts-node-docker
        expose:
          - '3000'
        ports:
          - '3000:3000'
        command: npm run start:dev
        networks:
          - postgres-network



networks:
  postgres-network:

